### ISSUE TITLE
Potential parser problem

### ISSUE THREAD

**Issue by Sigma-90** [heimrichhannot/contao-extassets#1]
I recently installed extassets and ran into a weird problem: None of my style rules apply, because the Less parser puts them inside a media query that never applies because it doesn't use an actual keyword but a generated crypto-string of some sort. It must be related to the inclusion of FontAwesome, because inside that media query are also duplicates of the FontAwesome classes. Plus, the first definition of the FontAwesome ruleset is also inside another, equally strange media query, while the rest of the generated code seems to be fine.

I ran quite few web searches to figure out what might be going on there but nothing useful came up so far, so I've decided to go directly to the source, hoping that you as the creator might have an idea what's causing this.

Here are excerpts of the two problematic sections in the generated css file:

Line 6239-7913:
```
@media b94ca40a799573b81dd6febda91ab138{
  /*!
   *  Font Awesome 4.2.0 by @davegandy - http://fontawesome.io - @fontawesome
   *  License - http://fontawesome.io/license (Font: SIL OFL 1.1, CSS: MIT License)
   */
  /* FONT PATH
   * -------------------------- */
  @font-face {
    ...
  }
  .fa{ ... }
...
}
```

Line 7914-EOF: 
```
@media d5d284fd68cb695e391fc1e248c6701a{
  .fa { ...} (notice the lack of any @font-face definition, the rest of the FA rules is all there, though)
  ...
  my style definitions from included less files
}
```

Another strange thing: When I deactivate FontAwesome in the external css group, only the first of the two above mentioned blocks is removed from the new generated file, the second block remains and it also still includes the FontAwesome definitions. I suspected this happened because the files were already downloaded to the server from before I deactived FontAwesome in the backend and thus still included, so I cleaned up all folders as described in the "Fehlerbehebung" section of the extension page, only to be greeted by an error 500. I checked the log file and it says this:
```
PHP Fatal error: Uncaught exception 'Less_Exception_Compiler' with message 'variable @fa-css-prefix is undefined in file anonymous-file-10946.less' thrown in /html/contao/vendor/oyejorge/less.php/lib/Less/Tree/Variable.php on line 49
```
So basically, deactivating FontAwesome doesn't seem to remove all dependencies, the parser still wants to use some parts from it and breaks when it doesn't find them. Not good.

I should mention that I run Contao 3.4. I know extassets is not yet cleared for that version but I doubt that this is the cause of the problem, as the less parser should be quite independent from that. It's a lot more likely that there is some conflict within the automatically downloaded source files, just like there was a couple of weeks ago when the back-then-current version of Bootstrap wouldn't compile because the .box-shadow-Mixin was removed but was still referenced somewhere else inside the files.

Now my deadline is drawing closer and no style I defined becomes visible unless I take the generated CSS file, remove the media query and reinclude it. And of course I have to repeat that every time a new one is generated. That tedious process costs me a lot of time and is definitely no long-term solution, so any help would be much appreciated.

**Comment by fatcrobat** [comment]
Strange, are you using the last version from packagist? Have you already tried to clear the less cache in the contao backend under system / maintenance?

**Comment by Sigma-90** [comment]
I did, but that didn't change anything. I figured out that as soon as I add just one single media query to my custom less files, the second media block is not generated by the parser and I can finally use them. However, the main FontAwesome block is still obscured by that invalid media query. But I had the duplicate FA classes available now, so I just had to copy the font-face definition from the obscured block and paste it into my files and now everything is working as intended. It's a hack though, so a real solution is still required. 
Did the Contao Devs add FontAwesome to v3.4 by default, by any chance? That might explain where the duplicate FA class definitions are coming from. And if the Less parser is intelligent enought to recognize the duplicates, the entire reason of those blocks might be the result of it's unresolved diff.

**Comment by fatcrobat** [comment]
I recently installed extassets with a fresh contao 3.4.4 version, added fontawesome and bootstrap support without ans issues. Please delete your assets/fontawesome and assets/bootstrap folder and clear the content of your assets/css folder. Than just open your page and both frameworks will be downloaded again. Make sure that in your page layout nothing is added as external css (this new contao core feature), just the extcss groups are injected.

**Comment by Sigma-90** [comment]
I actually did all of the above, but it kept happening anyway, Maybe one of the downloaded files had a mistake in it? But then again, I ran a complete search though the entire project and was unable to locate the source of the dupliucate fa class definitions, only the files in assets/font-awesome/css was found, no file that matches the included block (definining only the fa classes but no font-face definition), so I'm out of ideas as to where it might actually come from.

**Comment by fatcrobat** [comment]
Can you please update extassets? I upgraded the lessphp parser and changed the way external css groups will be combined. You are now able to use mixins and variables from other css groups inside your layout.
