### ISSUE TITLE
Bootstrap JS

### ISSUE THREAD

**Issue by AsfalothDE** [heimrichhannot/contao-extassets#5]
Ich habe eine Contao-Installation (3.5.12) und benutze Extassets. Die Extension ist super, aber seit dem Update auf Contao 3.5 und das damit verbundene Update auf Extassets 1.1.14 funktioniert die Einbindung von Bootstrap.js nicht länger. Ich habe in meiner Konfiguration für externes JS den Haken bei "Bootstrap JS" gesetzt, aber das Javascript von Bootstrap wird trotzdem nicht eingebunden. Ich habe bereits sämtliche Caches gelöscht, den components Ordner in assets (das hat früher meist geholfen) und die Extension neu installiert. Leider alles ohne Erfolg. Ist das eventuell ein Bug?

**Comment by fatcrobat** [comment]
Hallo, welche Version hattest du vorher installiert? Installation via composer? Ist die externe Javascript-Gruppe im Seitenlayout aktiv? Verfügt die fe_page.html5 über den Eintrag ```<?php echo $this->mootools; ?>```

**Comment by AsfalothDE** [comment]
Ich bin mir nicht 100% sicher, aber ich glaube, es war die Version 1.0.15. Contao lief in 3.3.x. Installiert hatte ich via Composer. Das externe JS wird geladen (ich habe vier Dateien darin, die alle zusammengemergt und geladen werden). Das Bootstrap.js befindet sich allerdings nicht in dieser Datei, nur die vier Dateien, die ich explizit angegeben habe.

**Comment by fatcrobat** [comment]
Da ist eine Menge passiert, aber die Kompatibilität sollte weiterhin gewährleistet sein. Bitte mal prüfen ob die Datei ```bootstrap.min.js``` & ```bootstrap.js``` im Ordner 'assets/components/bootstrap/js/' existiert. Weiterhin muss im Seitenlayout die externe JS-Gruppe ausgewählt werden und vorher in der JS-Gruppe ```Bootstrap javascript aktivieren``` aktiviert sein.

**Comment by AsfalothDE** [comment]
Die Verspätung tut mir leid, ich hatte die letzten beiden Tage keinen Zugang zum System. In der Zeit scheint sich der Fehler überdies von selbst gelöst zu haben - Bootstrap wird jetzt auf einmal inkludiert. Keine Ahnung, wie - aber es geht jetzt. Vielen Dank und sorry für die Umstände.
